name: Run Tests
on: [push]

jobs:
  build:
    runs-on: macos-latest
  
    strategy:
      matrix:
        seed: [1, 2, 3, 4, 5]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: brew install gcc boost cmake 
    
    # - run: find /opt/homebrew/Cellar/boost/1.87.0 -name "libboost_program_options.*"

    - name: Install GTest
      run: brew install googletest

    - run: echo "GTEST_ROOT=/opt/homebrew/opt/googletest/lib/cmake" >> $GITHUB_ENV
    - run: echo "BOOST_INCLUDE=/opt/homebrew/Cellar/boost/1.87.0/include" >> $GITHUB_ENV
    - run: echo "BOOST_LIB=/opt/homebrew/Cellar/boost/1.87.0/lib" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -S . -B build -DGTEST_ROOT=$GTEST_ROOT -DBOOST_INCLUDE=$BOOST_INCLUDE -DBOOST_LIB=$BOOST_LIB
    
    - name: Build
      run: cmake --build build

  
  test:
    runs-on: macos-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
        path: build

    - name: Run tests
      run: |
        echo "Running test with seed ${matrix.seed}"
        cd build && ctest --output-on-failure